Things to put on your resume:
Business Analytics Project Experience

Skills: Data Analytics, Quantitative Methods and etc.



Python as a calculator

In [1]:
2+1

3

In [3]:
2**3 #exponentiation

8

In [4]:
3/10

0

Python 3 would return .3 from 3/10 but Python 2 handles Floats differently - Integers return integers - you have to change to float for float
See below:

In [16]:
print(3.0/10)
print(3/10.0)
print(3*1.0/10)
print(float(3)/10)
3/10.0

0.3
0.3
0.3
0.3


0.3

In [23]:
counter = 100   # An integer assignment
miles = 1000.0  # A Floating point
name = "John"   # A string

print(counter)
print(miles)
print(name)


100
1000.0
John


In [27]:
a = b = c = 1 # sequential assignment
print a,b,c

a, b, c = 1, 2, 'John' # shorthand assignment
print a,b,c

1 1 1
1 2 John


In [30]:
print (a + b) #Arithmetic with variables
print (a + 10)
print (a/b)

3
11
0


In [32]:
c = a+b
print c

3


In [37]:
my_variable = 10
print (my_varable) # error message x is not defined  !!TYPO!!

NameError: name 'my_varaable' is not defined

Data types
int - integer
float - number with both integer and fractional
str - text - single or double quotes are ok
bool - boolean True or False (True and False are reserved words in python)

Declarations are case sensitive!!!  A is not a


In [43]:
str_1 = "Hello World!"

In [53]:
print (str_1)
print (str_1[0]) # Prints first character of the string **Indexing and Slicing
print (str_1[2:5]) # Print char 3-5 Include 2, 3, 4 Start at 2 and exclude after 5
print(str_1[2:])  # prints everything after the 2nd position
print(str_1 *2)
print (str_1 + ' TEST')


Hello world!
H
llo
llo world!
Hello world!Hello world!
Hello world! TEST


In [60]:
# Lists
a = 10
my_list = [a, 'abcd', 784, 2.23, 'john']
print my_list


[10, 'abcd', 784, 2.23, 'john']


In [62]:
tinylist = [123, 'john']
print tinylist * 2

[123, 'john', 123, 'john']


In [77]:
print my_list
print my_list[0]
print my_list[1:3]
print my_list[2:]

[10, 'abcd', 784, 2.23, 'john']
10
['abcd', 784]
[784, 2.23, 'john']


In [83]:
print my_list[-1] #print last record
len(my_list) # lenght of list - how many

john


5

In [85]:
myStart = 2
print my_list[myStart]

784


In [93]:
x = ['a', 'b', 'c', 'd'] #List manipulation
x[1]= "r" # Index 1
print(x)
x[2:] = ["s", "t"] # Slice from position 2 - you can add more
print(x)

['a', 'r', 'c', 'd']
['a', 'r', 's', 't']


In [95]:
x = ["a", "b", "c", "d"]
y = x + ["e","f"]
print y

['a', 'b', 'c', 'd', 'e', 'f']


In [97]:
x = ["a", "b", "c", "d"]
del(x[1])
print(x)

['a', 'c', 'd']


Packages - fun with packages


In [105]:
r = 0.3
import math
A = math.pi * r * r

In [104]:
print A

0.282743338823


In [101]:
print math.pi

3.14159265359


Selective Import - when you don't want to import the whole package (say it might take too long)

In [108]:
from math import pi
A = pi * r * r
print A

0.282743338823


In [114]:
from math import sqrt #only use square root fuction from math package
print sqrt(10)

3.16227766017


Numpy - package for data science and scientific computing with Python

In [115]:
import numpy as np #now you can use np to refer to Numpy package

In [121]:
baseball = [72, 78, 69, 71, 76, 69]

np_baseball = np.array(baseball)
print np_baseball

[72 78 69 71 76 69]


In [122]:
np_baseball

array([72, 78, 69, 71, 76, 69])

In [184]:
x = np.array([2,4,6,8])

In [125]:
print x + 1 # notice how this doesn't concat but adds 1 to each of the elements of the array

[3 5 7 9]


In [185]:
print x + x

[ 4  8 12 16]


In [145]:
height = np.array([72.0, 78.0, 69.0, 71.0, 76.0, 69.0])
height_meters = height * 0.0254
print height_meters


[1.8288 1.9812 1.7526 1.8034 1.9304 1.7526]


In [147]:
weight = np.array([180, 215, 210, 188, 176, 209])

In [148]:
weight_kg = weight * 0.43592

In [149]:
print weight_kg

[78.4656  93.7228  91.5432  81.95296 76.72192 91.10728]


In [150]:
baseball_bmi = weight_kg / (height_meters**2) 

In [151]:
print baseball_bmi

[23.46101914 23.87748694 29.80303377 25.19883794 20.58850655 29.66111456]


In [156]:
x = [4,9,6,3,1]
print x[1]


9


In [159]:
y = np.array(x)
print y[1]

9


In [160]:
print y[1:3]

[9 6]


In [164]:
my_index = np.array([True, True, False, False, True])
y[my_index]
print(y)

[4 9 6 3 1]


In [166]:
print(y)[my_index]

[4 9 1]


In [168]:
y > 5 # is the element less than 5 - so 1 is no, 2 is yes etc.  #Prof calls this "logical vector"

array([False,  True,  True, False, False])

In [169]:
high = y > 5

In [171]:
y[high]

array([9, 6])

Logical Operators in Python
> greater than,
>= greater than or equal to,
< less than,
<= less than or equal to,
== equal
!= not equal to,


In [172]:
print y

[4 9 6 3 1]


In [173]:
sub_y = y[[0,4,2]] #note the double brackets

In [174]:
print sub_y

[4 1 6]


In [187]:
print x
x = [[0,4,2]]

[[0, 4, 2]]


In [188]:
baseball

[72, 78, 69, 71, 76, 69]

In [189]:
np_baseball

array([72, 78, 69, 71, 76, 69])

In [192]:
list_2d = [[72, 78, 69, 71, 76, 69],[180, 215, 210, 188, 176, 209]]
np_2d = np.array(list_2d)
np_2d

array([[ 72,  78,  69,  71,  76,  69],
       [180, 215, 210, 188, 176, 209]])

In [196]:
print list_2d
print np_2d


[[72, 78, 69, 71, 76, 69], [180, 215, 210, 188, 176, 209]]
[[ 72  78  69  71  76  69]
 [180 215 210 188 176 209]]


In [197]:
np_2d.shape

(2L, 6L)

In [201]:
print np_2d[0] #first row

[72 78 69 71 76 69]


In [202]:
print np_2d[0][2] #print take 0 row, 3rd column

69


In [204]:
np_2d[0, 2] #print take 1st row (0), 3rd column (2)  This is the R/python way to do it

69

In [205]:
np_2d[:, 2:4] #take all rows and the 3rd column to the 4th column , a : stands for all the rows

array([[ 69,  71],
       [210, 188]])